### PR TITLE
MacOS troubleshooting info and script (fix #28)

### LINKED ISSUE #28: make test-cover: su: unknown user <local username>
Where `dac.chartrand` is my username on OSX.

```
$ make test-cover

docker-compose run --rm --user "0:0" -e 'XDEBUG_MODE=coverage' app sh -c 'echo "XDebug installing, please wait.." \
		&& apk --no-cache add autoconf make g++ 1>/dev/null && pecl install xdebug-3.0.4 1>/dev/null \
		&& docker-php-ext-enable xdebug 1>/dev/null \
		&& su dac.chartrand -s /bin/sh -c "composer phpunit"'
Creating laravel-roadrunner-in-docker_app_run ... done
XDebug installing, please wait..
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
su: unknown user dac.chartrand
ERROR: 1
make: *** [test-cover] Error 1
```

### PR DESCRIPTION
**Pull request by connerbw**
## Description

Add MacOS troubleshooting info in README and `./scripts/fix_mac_user.sh` to create mac_passwd file and reconfigure docker-compose.yml to use it.

Fixes #28

### CODE REVIEW

**Comment by tarampampam** [comment]
What do you think about commenting line for MacOS users:

https://github.com/tarampampam/laravel-roadrunner-in-docker/blob/8273848accc3da95181ecaa33df56b2b23b81320/docker-compose.yml#L26

This will break the working?

**Comment by connerbw** [comment]
Commenting out:

```
    volumes:
      # - ./mac_passwd:/etc/passwd:ro
```

Doesn't work:

Screen Shot 2021-05-21 at 11 42 38 AM

The crux of the issue is that the `Makefile` uses `DC_RUN_ARGS = --rm --user "$(shell id -u):$(shell id -g)"` in most of commands, so it's looking for my `dac.chartrand` user, but can't find it.

**Comment by tarampampam** [comment]
Could you please leave only the text description in the readme file (without a script and `.gitignore` file changes)?

**Comment by connerbw** [comment]
Sorry for not responding. Thanks for taking care of this.

**Pull request merged**
