### PR TITLE
 Laravel updated up to 10 (from 9)

### PR DESCRIPTION
**Pull request by tafhyseni**
## Description

Upgraded the Laravel framework to the latest official release Laravel 10.5.1

### CODE REVIEW

**Comment by tarampampam** [comment]
Thanks for the reminder about the update. As you can see - that's not too easy to update the major laravel version. But don't worry - I will update your PR shortly, do nothing, please.

**Comment by tarampampam** [comment]
@tafhyseni Thank you so much for your contribution! 😆

**Comment by tafhyseni** [comment]
Got a question and sorry for making it here. 

As for using this configuration into an existing Laravel Application I think the docs in the readme is not working because there is no Spcial Tag in there. 

Can you please provide some useful info in that regard?

**Comment by tarampampam** [comment]
@tafhyseni I's sorry, but I don't understand you... What do u mean, and what I should do?

**Comment by tafhyseni** [comment]
> @tafhyseni I's sorry, but I don't understand you... What do u mean, and what I should do?

Wanted more information about using this docker configuration in an existing laravel application. 

Is that kind of information available?

**Comment by tarampampam** [comment]
Oh, sure! You can watch the readme file here - https://github.com/roadrunner-php/laravel-bridge (the most crucial package to integrate the RR with Laravel).

And watch the dockerfile in this repo. It will be enough to understand how it works at all, I believe.

**Pull request merged**
